name: Packtracker.io
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: fake .env configuration for local
        run: cp ".env.example" ".env"

      - name: report webpack stats
        uses: packtracker/report@2.2.7
        env:
          PT_PROJECT_TOKEN: d23eafa4-20b9-4f5d-b3f6-8f3f49e13092
          WEBPACK_CONFIG_PATH: ./node_modules/@vue/cli-service/webpack.config.js
