name: relative CI - webpack stats

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: npm run build --if-present
      - run: npx relative-ci-agent
        env:
          RELATIVE_CI_KEY: "9fb2ccb0-eec3-11ea-b455-f18cf0efd406"
